/*
 * Definancy Node API
 * Specification version: 0.0.1.wip.20250826
 *
 * NOTE: This class is auto generated by our custom generator.
 * Do not edit the class manually.
 */


package com.definancy.model;

import java.util.Objects;
import java.util.Locale;
import com.definancy.model.Amount;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Locale;

import com.definancy.JSON;

/**
 * AcceptancePaymentTrait
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-09-24T14:07:22.312732801Z[Etc/UTC]", comments = "Generator version: 7.16.0-SNAPSHOT")
public class AcceptancePaymentTrait {
  public static final String SERIALIZED_NAME_MIN_AMOUNT = "min-amount";
  @SerializedName(SERIALIZED_NAME_MIN_AMOUNT)
  @javax.annotation.Nullable
  private Amount minAmount;

  public static final String SERIALIZED_NAME_MAX_AMOUNT = "max-amount";
  @SerializedName(SERIALIZED_NAME_MAX_AMOUNT)
  @javax.annotation.Nullable
  private Amount maxAmount;

  public AcceptancePaymentTrait() {
  }

  public AcceptancePaymentTrait minAmount(@javax.annotation.Nullable Amount minAmount) {
    this.minAmount = minAmount;
    return this;
  }

  /**
   * Get minAmount
   * @return minAmount
   */
  @javax.annotation.Nullable
  public Amount getMinAmount() {
    return minAmount;
  }

  public void setMinAmount(@javax.annotation.Nullable Amount minAmount) {
    this.minAmount = minAmount;
  }


  public AcceptancePaymentTrait maxAmount(@javax.annotation.Nullable Amount maxAmount) {
    this.maxAmount = maxAmount;
    return this;
  }

  /**
   * Get maxAmount
   * @return maxAmount
   */
  @javax.annotation.Nullable
  public Amount getMaxAmount() {
    return maxAmount;
  }

  public void setMaxAmount(@javax.annotation.Nullable Amount maxAmount) {
    this.maxAmount = maxAmount;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AcceptancePaymentTrait acceptancePaymentTrait = (AcceptancePaymentTrait) o;
    return Objects.equals(this.minAmount, acceptancePaymentTrait.minAmount) &&
        Objects.equals(this.maxAmount, acceptancePaymentTrait.maxAmount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(minAmount, maxAmount);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AcceptancePaymentTrait {\n");
    sb.append("    minAmount: ").append(toIndentedString(minAmount)).append("\n");
    sb.append("    maxAmount: ").append(toIndentedString(maxAmount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("min-amount", "max-amount"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to AcceptancePaymentTrait
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!AcceptancePaymentTrait.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field(s) %s in AcceptancePaymentTrait is not found in the empty JSON string", AcceptancePaymentTrait.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!AcceptancePaymentTrait.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The field `%s` in the JSON string is not defined in the `AcceptancePaymentTrait` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `min-amount`
      if (jsonObj.get("min-amount") != null && !jsonObj.get("min-amount").isJsonNull()) {
        Amount.validateJsonElement(jsonObj.get("min-amount"));
      }
      // validate the optional field `max-amount`
      if (jsonObj.get("max-amount") != null && !jsonObj.get("max-amount").isJsonNull()) {
        Amount.validateJsonElement(jsonObj.get("max-amount"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!AcceptancePaymentTrait.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'AcceptancePaymentTrait' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<AcceptancePaymentTrait> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(AcceptancePaymentTrait.class));

       return (TypeAdapter<T>) new TypeAdapter<AcceptancePaymentTrait>() {
           @Override
           public void write(JsonWriter out, AcceptancePaymentTrait value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public AcceptancePaymentTrait read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of AcceptancePaymentTrait given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of AcceptancePaymentTrait
   * @throws IOException if the JSON string is invalid with respect to AcceptancePaymentTrait
   */
  public static AcceptancePaymentTrait fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, AcceptancePaymentTrait.class);
  }

  /**
   * Convert an instance of AcceptancePaymentTrait to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

