/*
 * Definancy API
 * REST API for managing asset, network and contract configurations, and vault-based financial operations. This API provides a comprehensive set of endpoints for health monitoring, network management, asset  configuration, contract management, vault lifecycle management, and QR-Code generation. It is designed to facilitate seamless integration with financial systems, ensuring secure and efficient payment  processing while maintaining strict compliance standards.
 *
 * The version of the OpenAPI document: 0.0.1.wip.20250925
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.definancy.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.util.Objects;
import java.util.StringJoiner;

/** AmountRaw */
@JsonPropertyOrder({AmountRaw.JSON_PROPERTY_RAW, AmountRaw.JSON_PROPERTY_DECIMALS})
@javax.annotation.Generated(
        value = "org.openapitools.codegen.languages.JavaClientCodegen",
        comments = "Generator version: 7.20.0")
public class AmountRaw {
    public static final String JSON_PROPERTY_RAW = "raw";
    @javax.annotation.Nonnull private String raw;

    public static final String JSON_PROPERTY_DECIMALS = "decimals";
    @javax.annotation.Nonnull private Integer decimals;

    public AmountRaw() {}

    /** Constructor with all args parameters */
    public AmountRaw(
            @JsonProperty(value = JSON_PROPERTY_RAW, required = true) String raw,
            @JsonProperty(value = JSON_PROPERTY_DECIMALS, required = true) Integer decimals) {
        this.raw = raw;
        this.decimals = decimals;
    }

    public AmountRaw raw(@javax.annotation.Nonnull String raw) {

        this.raw = raw;
        return this;
    }

    /**
     * String representation of a non-negative integer used for precise handling of large numbers
     * without floating-point precision issues. Supports values up to 78 digits to accommodate
     * various asset denominations and high-precision calculations.
     *
     * @return raw
     */
    @javax.annotation.Nonnull
    @JsonProperty(value = JSON_PROPERTY_RAW, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public String getRaw() {
        return raw;
    }

    @JsonProperty(value = JSON_PROPERTY_RAW, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setRaw(@javax.annotation.Nonnull String raw) {
        this.raw = raw;
    }

    public AmountRaw decimals(@javax.annotation.Nonnull Integer decimals) {

        this.decimals = decimals;
        return this;
    }

    /**
     * Number of decimal places used for displaying amounts. For example, USDC typically uses 6
     * decimals, while Ethereum uses 18. This determines how the raw value should be formatted for
     * user presentation. minimum: 0 maximum: 77
     *
     * @return decimals
     */
    @javax.annotation.Nonnull
    @JsonProperty(value = JSON_PROPERTY_DECIMALS, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public Integer getDecimals() {
        return decimals;
    }

    @JsonProperty(value = JSON_PROPERTY_DECIMALS, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setDecimals(@javax.annotation.Nonnull Integer decimals) {
        this.decimals = decimals;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        AmountRaw amountRaw = (AmountRaw) o;
        return Objects.equals(this.raw, amountRaw.raw)
                && Objects.equals(this.decimals, amountRaw.decimals);
    }

    @Override
    public int hashCode() {
        return Objects.hash(raw, decimals);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class AmountRaw {\n");
        sb.append("    raw: ").append(toIndentedString(raw)).append("\n");
        sb.append("    decimals: ").append(toIndentedString(decimals)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces (except the first
     * line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    /**
     * Convert the instance into URL query string.
     *
     * @return URL query string
     */
    public String toUrlQueryString() {
        return toUrlQueryString(null);
    }

    /**
     * Convert the instance into URL query string.
     *
     * @param prefix prefix of the query string
     * @return URL query string
     */
    public String toUrlQueryString(String prefix) {
        String suffix = "";
        String containerSuffix = "";
        String containerPrefix = "";
        if (prefix == null) {
            // style=form, explode=true, e.g. /pet?name=cat&type=manx
            prefix = "";
        } else {
            // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
            prefix = prefix + "[";
            suffix = "]";
            containerSuffix = "]";
            containerPrefix = "[";
        }

        StringJoiner joiner = new StringJoiner("&");

        // add `raw` to the URL query string
        if (getRaw() != null) {
            try {
                joiner.add(
                        String.format(
                                java.util.Locale.ROOT,
                                "%sraw%s=%s",
                                prefix,
                                suffix,
                                URLEncoder.encode(String.valueOf(getRaw()), "UTF-8")
                                        .replaceAll("\\+", "%20")));
            } catch (UnsupportedEncodingException e) {
                // Should never happen, UTF-8 is always supported
                throw new RuntimeException(e);
            }
        }

        // add `decimals` to the URL query string
        if (getDecimals() != null) {
            try {
                joiner.add(
                        String.format(
                                java.util.Locale.ROOT,
                                "%sdecimals%s=%s",
                                prefix,
                                suffix,
                                URLEncoder.encode(String.valueOf(getDecimals()), "UTF-8")
                                        .replaceAll("\\+", "%20")));
            } catch (UnsupportedEncodingException e) {
                // Should never happen, UTF-8 is always supported
                throw new RuntimeException(e);
            }
        }

        return joiner.toString();
    }

    public static class Builder {

        private AmountRaw instance;

        public Builder() {
            this(new AmountRaw());
        }

        protected Builder(AmountRaw instance) {
            this.instance = instance;
        }

        public AmountRaw.Builder raw(String raw) {
            this.instance.raw = raw;
            return this;
        }

        public AmountRaw.Builder decimals(Integer decimals) {
            this.instance.decimals = decimals;
            return this;
        }

        /**
         * returns a built AmountRaw instance.
         *
         * <p>The builder is not reusable.
         */
        public AmountRaw build() {
            try {
                return this.instance;
            } finally {
                // ensure that this.instance is not reused
                this.instance = null;
            }
        }

        @Override
        public String toString() {
            return getClass() + "=(" + instance + ")";
        }
    }

    /** Create a builder with no initialized field. */
    public static AmountRaw.Builder builder() {
        return new AmountRaw.Builder();
    }

    /** Create a builder with a shallow copy of this instance. */
    public AmountRaw.Builder toBuilder() {
        return new AmountRaw.Builder().raw(getRaw()).decimals(getDecimals());
    }
}
