/*
 * Definancy API
 * Specification version: 0.0.1.wip.20250925
 *
 * NOTE: This class is auto generated by our custom generator.
 * Do not edit the class manually.
 */


package com.definancy.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.definancy.JSON;


/**
 * AmountRaw
 */
@JsonPropertyOrder({
  AmountRaw.JSON_PROPERTY_RAW,
  AmountRaw.JSON_PROPERTY_DECIMALS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.16.0-SNAPSHOT")
public class AmountRaw {
  public static final String JSON_PROPERTY_RAW = "raw";
  @javax.annotation.Nonnull
  private String raw;

  public static final String JSON_PROPERTY_DECIMALS = "decimals";
  @javax.annotation.Nonnull
  private Integer decimals;

  public AmountRaw() { 
  }

  public AmountRaw raw(@javax.annotation.Nonnull String raw) {
    this.raw = raw;
    return this;
  }

  /**
   * String representation of a non-negative integer used for precise handling of large numbers without floating-point precision issues. Supports values up to 78 digits to accommodate various asset denominations and high-precision calculations.
   * @return raw
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_RAW, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getRaw() {
    return raw;
  }


  @JsonProperty(value = JSON_PROPERTY_RAW, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRaw(@javax.annotation.Nonnull String raw) {
    this.raw = raw;
  }


  public AmountRaw decimals(@javax.annotation.Nonnull Integer decimals) {
    this.decimals = decimals;
    return this;
  }

  /**
   * Number of decimal places used for displaying amounts. For example, USDC typically uses 6 decimals, while Ethereum uses 18. This determines how the raw value should be formatted for user presentation.
   * minimum: 0
   * maximum: 77
   * @return decimals
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_DECIMALS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getDecimals() {
    return decimals;
  }


  @JsonProperty(value = JSON_PROPERTY_DECIMALS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDecimals(@javax.annotation.Nonnull Integer decimals) {
    this.decimals = decimals;
  }


  /**
   * Return true if this AmountRaw object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AmountRaw amountRaw = (AmountRaw) o;
    return Objects.equals(this.raw, amountRaw.raw) &&
        Objects.equals(this.decimals, amountRaw.decimals);
  }

  @Override
  public int hashCode() {
    return Objects.hash(raw, decimals);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AmountRaw {\n");
    sb.append("    raw: ").append(toIndentedString(raw)).append("\n");
    sb.append("    decimals: ").append(toIndentedString(decimals)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

