/*
 * Definancy API
 * Specification version: 0.0.1.wip.20250925
 *
 * NOTE: This class is auto generated by our custom generator.
 * Do not edit the class manually.
 */


package com.definancy.model;

import java.util.Objects;
import java.util.Locale;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Locale;

import com.definancy.JSON;

/**
 * Confirmation progress information for transactions in the confirming state, providing current status and estimated completion time for full confirmation.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.16.0-SNAPSHOT")
public class BlockchainConfirmationStats {
  public static final String SERIALIZED_NAME_CONFIRMED = "confirmed";
  @SerializedName(SERIALIZED_NAME_CONFIRMED)
  @javax.annotation.Nonnull
  private Integer confirmed;

  public static final String SERIALIZED_NAME_REMAINING = "remaining";
  @SerializedName(SERIALIZED_NAME_REMAINING)
  @javax.annotation.Nonnull
  private Integer remaining;

  public static final String SERIALIZED_NAME_ETA = "eta";
  @SerializedName(SERIALIZED_NAME_ETA)
  @javax.annotation.Nonnull
  private Integer eta;

  public BlockchainConfirmationStats() {
  }

  public BlockchainConfirmationStats confirmed(@javax.annotation.Nonnull Integer confirmed) {
    this.confirmed = confirmed;
    return this;
  }

  /**
   * Number of blockchain confirmations observed for a transaction, indicating the level of network consensus and security. Higher numbers provide greater confidence in transaction finality.
   * minimum: 0
   * maximum: 65535
   * @return confirmed
   */
  @javax.annotation.Nonnull
  public Integer getConfirmed() {
    return confirmed;
  }

  public void setConfirmed(@javax.annotation.Nonnull Integer confirmed) {
    this.confirmed = confirmed;
  }


  public BlockchainConfirmationStats remaining(@javax.annotation.Nonnull Integer remaining) {
    this.remaining = remaining;
    return this;
  }

  /**
   * Number of blockchain confirmations observed for a transaction, indicating the level of network consensus and security. Higher numbers provide greater confidence in transaction finality.
   * minimum: 0
   * maximum: 65535
   * @return remaining
   */
  @javax.annotation.Nonnull
  public Integer getRemaining() {
    return remaining;
  }

  public void setRemaining(@javax.annotation.Nonnull Integer remaining) {
    this.remaining = remaining;
  }


  public BlockchainConfirmationStats eta(@javax.annotation.Nonnull Integer eta) {
    this.eta = eta;
    return this;
  }

  /**
   * UNIX timestamp in milliseconds representing a specific point in time. Used for tracking creation dates, expiration times, transaction timestamps, and other time-sensitive operations throughout the payment lifecycle.
   * minimum: 0
   * @return eta
   */
  @javax.annotation.Nonnull
  public Integer getEta() {
    return eta;
  }

  public void setEta(@javax.annotation.Nonnull Integer eta) {
    this.eta = eta;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BlockchainConfirmationStats blockchainConfirmationStats = (BlockchainConfirmationStats) o;
    return Objects.equals(this.confirmed, blockchainConfirmationStats.confirmed) &&
        Objects.equals(this.remaining, blockchainConfirmationStats.remaining) &&
        Objects.equals(this.eta, blockchainConfirmationStats.eta);
  }

  @Override
  public int hashCode() {
    return Objects.hash(confirmed, remaining, eta);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BlockchainConfirmationStats {\n");
    sb.append("    confirmed: ").append(toIndentedString(confirmed)).append("\n");
    sb.append("    remaining: ").append(toIndentedString(remaining)).append("\n");
    sb.append("    eta: ").append(toIndentedString(eta)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("confirmed", "remaining", "eta"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("confirmed", "remaining", "eta"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to BlockchainConfirmationStats
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!BlockchainConfirmationStats.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field(s) %s in BlockchainConfirmationStats is not found in the empty JSON string", BlockchainConfirmationStats.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!BlockchainConfirmationStats.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The field `%s` in the JSON string is not defined in the `BlockchainConfirmationStats` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : BlockchainConfirmationStats.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!BlockchainConfirmationStats.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'BlockchainConfirmationStats' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<BlockchainConfirmationStats> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(BlockchainConfirmationStats.class));

       return (TypeAdapter<T>) new TypeAdapter<BlockchainConfirmationStats>() {
           @Override
           public void write(JsonWriter out, BlockchainConfirmationStats value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public BlockchainConfirmationStats read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of BlockchainConfirmationStats given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of BlockchainConfirmationStats
   * @throws IOException if the JSON string is invalid with respect to BlockchainConfirmationStats
   */
  public static BlockchainConfirmationStats fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, BlockchainConfirmationStats.class);
  }

  /**
   * Convert an instance of BlockchainConfirmationStats to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

