/*
 * Definancy API
 * Specification version: 0.0.1.wip.20250925
 *
 * NOTE: This class is auto generated by our custom generator.
 * Do not edit the class manually.
 */


package com.definancy.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import java.util.Locale;
import com.definancy.model.Media;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.definancy.JSON;


/**
 * ContractMediaMap
 */
@JsonPropertyOrder({
  ContractMediaMap.JSON_PROPERTY_LOGO_LIGHT,
  ContractMediaMap.JSON_PROPERTY_LOGO_DARK
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.16.0-SNAPSHOT")
public class ContractMediaMap {
  public static final String JSON_PROPERTY_LOGO_LIGHT = "logo-light";
  @javax.annotation.Nonnull
  private Media logoLight;

  public static final String JSON_PROPERTY_LOGO_DARK = "logo-dark";
  @javax.annotation.Nonnull
  private Media logoDark;

  public ContractMediaMap() { 
  }

  public ContractMediaMap logoLight(@javax.annotation.Nonnull Media logoLight) {
    this.logoLight = logoLight;
    return this;
  }

  /**
   * Get logoLight
   * @return logoLight
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_LOGO_LIGHT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Media getLogoLight() {
    return logoLight;
  }


  @JsonProperty(value = JSON_PROPERTY_LOGO_LIGHT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLogoLight(@javax.annotation.Nonnull Media logoLight) {
    this.logoLight = logoLight;
  }


  public ContractMediaMap logoDark(@javax.annotation.Nonnull Media logoDark) {
    this.logoDark = logoDark;
    return this;
  }

  /**
   * Get logoDark
   * @return logoDark
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_LOGO_DARK, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Media getLogoDark() {
    return logoDark;
  }


  @JsonProperty(value = JSON_PROPERTY_LOGO_DARK, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLogoDark(@javax.annotation.Nonnull Media logoDark) {
    this.logoDark = logoDark;
  }


  /**
   * Return true if this ContractMediaMap object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ContractMediaMap contractMediaMap = (ContractMediaMap) o;
    return Objects.equals(this.logoLight, contractMediaMap.logoLight) &&
        Objects.equals(this.logoDark, contractMediaMap.logoDark);
  }

  @Override
  public int hashCode() {
    return Objects.hash(logoLight, logoDark);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ContractMediaMap {\n");
    sb.append("    logoLight: ").append(toIndentedString(logoLight)).append("\n");
    sb.append("    logoDark: ").append(toIndentedString(logoDark)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

