/*
 * Definancy API
 * Specification version: 0.0.1.wip.20250925
 *
 * NOTE: This class is auto generated by our custom generator.
 * Do not edit the class manually.
 */


package com.definancy.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import java.util.Locale;
import com.definancy.model.ContractConfig;
import com.definancy.model.ContractId;
import com.definancy.model.ContractInfo;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.definancy.JSON;


/**
 * Complete contract definition combining identification, metadata, and configuration. Represents a deployed contract that can process payments for a specific asset on a specific blockchain network.
 */
@JsonPropertyOrder({
  Contract.JSON_PROPERTY_ID,
  Contract.JSON_PROPERTY_INFO,
  Contract.JSON_PROPERTY_CONFIG
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.16.0-SNAPSHOT")
public class Contract {
  public static final String JSON_PROPERTY_ID = "id";
  @javax.annotation.Nonnull
  private ContractId id;

  public static final String JSON_PROPERTY_INFO = "info";
  @javax.annotation.Nonnull
  private ContractInfo info;

  public static final String JSON_PROPERTY_CONFIG = "config";
  @javax.annotation.Nonnull
  private ContractConfig config;

  public Contract() { 
  }

  public Contract id(@javax.annotation.Nonnull ContractId id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ContractId getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(@javax.annotation.Nonnull ContractId id) {
    this.id = id;
  }


  public Contract info(@javax.annotation.Nonnull ContractInfo info) {
    this.info = info;
    return this;
  }

  /**
   * Get info
   * @return info
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_INFO, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ContractInfo getInfo() {
    return info;
  }


  @JsonProperty(value = JSON_PROPERTY_INFO, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setInfo(@javax.annotation.Nonnull ContractInfo info) {
    this.info = info;
  }


  public Contract config(@javax.annotation.Nonnull ContractConfig config) {
    this.config = config;
    return this;
  }

  /**
   * Get config
   * @return config
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CONFIG, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ContractConfig getConfig() {
    return config;
  }


  @JsonProperty(value = JSON_PROPERTY_CONFIG, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setConfig(@javax.annotation.Nonnull ContractConfig config) {
    this.config = config;
  }


  /**
   * Return true if this Contract object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Contract contract = (Contract) o;
    return Objects.equals(this.id, contract.id) &&
        Objects.equals(this.info, contract.info) &&
        Objects.equals(this.config, contract.config);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, info, config);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Contract {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    info: ").append(toIndentedString(info)).append("\n");
    sb.append("    config: ").append(toIndentedString(config)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

