/*
 * Definancy API
 * REST API for managing asset, network and contract configurations, and vault-based financial operations. This API provides a comprehensive set of endpoints for health monitoring, network management, asset  configuration, contract management, vault lifecycle management, and QR-Code generation. It is designed to facilitate seamless integration with financial systems, ensuring secure and efficient payment  processing while maintaining strict compliance standards.
 *
 * The version of the OpenAPI document: 0.0.1.wip.20250925
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.definancy.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.util.Objects;
import java.util.StringJoiner;

/** Document validation state. */
@JsonPropertyOrder({
    DocumentStatus.JSON_PROPERTY_ID,
    DocumentStatus.JSON_PROPERTY_DETAILS,
    DocumentStatus.JSON_PROPERTY_EXPIRE
})
@javax.annotation.Generated(
        value = "org.openapitools.codegen.languages.JavaClientCodegen",
        comments = "Generator version: 7.20.0")
public class DocumentStatus {
    public static final String JSON_PROPERTY_ID = "id";
    @javax.annotation.Nonnull private DocumentStatusId id;

    public static final String JSON_PROPERTY_DETAILS = "details";
    @javax.annotation.Nonnull private String details;

    public static final String JSON_PROPERTY_EXPIRE = "expire";
    @javax.annotation.Nullable private Expire expire;

    public DocumentStatus() {}

    /** Constructor with all args parameters */
    public DocumentStatus(
            @JsonProperty(value = JSON_PROPERTY_ID, required = true) DocumentStatusId id,
            @JsonProperty(value = JSON_PROPERTY_DETAILS, required = true) String details,
            @JsonProperty(value = JSON_PROPERTY_EXPIRE, required = false) Expire expire) {
        this.id = id;
        this.details = details;
        this.expire = expire;
    }

    public DocumentStatus id(@javax.annotation.Nonnull DocumentStatusId id) {

        this.id = id;
        return this;
    }

    /**
     * Get id
     *
     * @return id
     */
    @javax.annotation.Nonnull
    @JsonProperty(value = JSON_PROPERTY_ID, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public DocumentStatusId getId() {
        return id;
    }

    @JsonProperty(value = JSON_PROPERTY_ID, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setId(@javax.annotation.Nonnull DocumentStatusId id) {
        this.id = id;
    }

    public DocumentStatus details(@javax.annotation.Nonnull String details) {

        this.details = details;
        return this;
    }

    /**
     * Human-readable validation details.
     *
     * @return details
     */
    @javax.annotation.Nonnull
    @JsonProperty(value = JSON_PROPERTY_DETAILS, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public String getDetails() {
        return details;
    }

    @JsonProperty(value = JSON_PROPERTY_DETAILS, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setDetails(@javax.annotation.Nonnull String details) {
        this.details = details;
    }

    public DocumentStatus expire(@javax.annotation.Nullable Expire expire) {

        this.expire = expire;
        return this;
    }

    /**
     * Get expire
     *
     * @return expire
     */
    @javax.annotation.Nullable
    @JsonProperty(value = JSON_PROPERTY_EXPIRE, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public Expire getExpire() {
        return expire;
    }

    @JsonProperty(value = JSON_PROPERTY_EXPIRE, required = false)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setExpire(@javax.annotation.Nullable Expire expire) {
        this.expire = expire;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        DocumentStatus documentStatus = (DocumentStatus) o;
        return Objects.equals(this.id, documentStatus.id)
                && Objects.equals(this.details, documentStatus.details)
                && Objects.equals(this.expire, documentStatus.expire);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, details, expire);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class DocumentStatus {\n");
        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    details: ").append(toIndentedString(details)).append("\n");
        sb.append("    expire: ").append(toIndentedString(expire)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces (except the first
     * line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    /**
     * Convert the instance into URL query string.
     *
     * @return URL query string
     */
    public String toUrlQueryString() {
        return toUrlQueryString(null);
    }

    /**
     * Convert the instance into URL query string.
     *
     * @param prefix prefix of the query string
     * @return URL query string
     */
    public String toUrlQueryString(String prefix) {
        String suffix = "";
        String containerSuffix = "";
        String containerPrefix = "";
        if (prefix == null) {
            // style=form, explode=true, e.g. /pet?name=cat&type=manx
            prefix = "";
        } else {
            // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
            prefix = prefix + "[";
            suffix = "]";
            containerSuffix = "]";
            containerPrefix = "[";
        }

        StringJoiner joiner = new StringJoiner("&");

        // add `id` to the URL query string
        if (getId() != null) {
            try {
                joiner.add(
                        String.format(
                                java.util.Locale.ROOT,
                                "%sid%s=%s",
                                prefix,
                                suffix,
                                URLEncoder.encode(String.valueOf(getId()), "UTF-8")
                                        .replaceAll("\\+", "%20")));
            } catch (UnsupportedEncodingException e) {
                // Should never happen, UTF-8 is always supported
                throw new RuntimeException(e);
            }
        }

        // add `details` to the URL query string
        if (getDetails() != null) {
            try {
                joiner.add(
                        String.format(
                                java.util.Locale.ROOT,
                                "%sdetails%s=%s",
                                prefix,
                                suffix,
                                URLEncoder.encode(String.valueOf(getDetails()), "UTF-8")
                                        .replaceAll("\\+", "%20")));
            } catch (UnsupportedEncodingException e) {
                // Should never happen, UTF-8 is always supported
                throw new RuntimeException(e);
            }
        }

        // add `expire` to the URL query string
        if (getExpire() != null) {
            joiner.add(getExpire().toUrlQueryString(prefix + "expire" + suffix));
        }

        return joiner.toString();
    }

    public static class Builder {

        private DocumentStatus instance;

        public Builder() {
            this(new DocumentStatus());
        }

        protected Builder(DocumentStatus instance) {
            this.instance = instance;
        }

        public DocumentStatus.Builder id(DocumentStatusId id) {
            this.instance.id = id;
            return this;
        }

        public DocumentStatus.Builder details(String details) {
            this.instance.details = details;
            return this;
        }

        public DocumentStatus.Builder expire(Expire expire) {
            this.instance.expire = expire;
            return this;
        }

        /**
         * returns a built DocumentStatus instance.
         *
         * <p>The builder is not reusable.
         */
        public DocumentStatus build() {
            try {
                return this.instance;
            } finally {
                // ensure that this.instance is not reused
                this.instance = null;
            }
        }

        @Override
        public String toString() {
            return getClass() + "=(" + instance + ")";
        }
    }

    /** Create a builder with no initialized field. */
    public static DocumentStatus.Builder builder() {
        return new DocumentStatus.Builder();
    }

    /** Create a builder with a shallow copy of this instance. */
    public DocumentStatus.Builder toBuilder() {
        return new DocumentStatus.Builder().id(getId()).details(getDetails()).expire(getExpire());
    }
}
