/*
 * Definancy API
 * REST API for managing asset, network and contract configurations, and vault-based financial operations. This API provides a comprehensive set of endpoints for health monitoring, network management, asset  configuration, contract management, vault lifecycle management, and QR-Code generation. It is designed to facilitate seamless integration with financial systems, ensuring secure and efficient payment  processing while maintaining strict compliance standards.
 *
 * The version of the OpenAPI document: 0.0.1.wip.20250925
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.definancy.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.util.Objects;
import java.util.StringJoiner;

/** Document content specification. */
@JsonPropertyOrder({DocumentConfigBase.JSON_PROPERTY_TYPE})
@javax.annotation.Generated(
        value = "org.openapitools.codegen.languages.JavaClientCodegen",
        comments = "Generator version: 7.20.0")
public class DocumentConfigBase {
    public static final String JSON_PROPERTY_TYPE = "type";
    @javax.annotation.Nonnull private DocumentType type;

    public DocumentConfigBase() {}

    /** Constructor with all args parameters */
    public DocumentConfigBase(
            @JsonProperty(value = JSON_PROPERTY_TYPE, required = true) DocumentType type) {
        this.type = type;
    }

    public DocumentConfigBase type(@javax.annotation.Nonnull DocumentType type) {

        this.type = type;
        return this;
    }

    /**
     * Get type
     *
     * @return type
     */
    @javax.annotation.Nonnull
    @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public DocumentType getType() {
        return type;
    }

    @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setType(@javax.annotation.Nonnull DocumentType type) {
        this.type = type;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        DocumentConfigBase documentConfigBase = (DocumentConfigBase) o;
        return Objects.equals(this.type, documentConfigBase.type);
    }

    @Override
    public int hashCode() {
        return Objects.hash(type);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class DocumentConfigBase {\n");
        sb.append("    type: ").append(toIndentedString(type)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces (except the first
     * line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    /**
     * Convert the instance into URL query string.
     *
     * @return URL query string
     */
    public String toUrlQueryString() {
        return toUrlQueryString(null);
    }

    /**
     * Convert the instance into URL query string.
     *
     * @param prefix prefix of the query string
     * @return URL query string
     */
    public String toUrlQueryString(String prefix) {
        String suffix = "";
        String containerSuffix = "";
        String containerPrefix = "";
        if (prefix == null) {
            // style=form, explode=true, e.g. /pet?name=cat&type=manx
            prefix = "";
        } else {
            // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
            prefix = prefix + "[";
            suffix = "]";
            containerSuffix = "]";
            containerPrefix = "[";
        }

        StringJoiner joiner = new StringJoiner("&");

        // add `type` to the URL query string
        if (getType() != null) {
            try {
                joiner.add(
                        String.format(
                                java.util.Locale.ROOT,
                                "%stype%s=%s",
                                prefix,
                                suffix,
                                URLEncoder.encode(String.valueOf(getType()), "UTF-8")
                                        .replaceAll("\\+", "%20")));
            } catch (UnsupportedEncodingException e) {
                // Should never happen, UTF-8 is always supported
                throw new RuntimeException(e);
            }
        }

        return joiner.toString();
    }

    public static class Builder {

        private DocumentConfigBase instance;

        public Builder() {
            this(new DocumentConfigBase());
        }

        protected Builder(DocumentConfigBase instance) {
            this.instance = instance;
        }

        public DocumentConfigBase.Builder type(DocumentType type) {
            this.instance.type = type;
            return this;
        }

        /**
         * returns a built DocumentConfigBase instance.
         *
         * <p>The builder is not reusable.
         */
        public DocumentConfigBase build() {
            try {
                return this.instance;
            } finally {
                // ensure that this.instance is not reused
                this.instance = null;
            }
        }

        @Override
        public String toString() {
            return getClass() + "=(" + instance + ")";
        }
    }

    /** Create a builder with no initialized field. */
    public static DocumentConfigBase.Builder builder() {
        return new DocumentConfigBase.Builder();
    }

    /** Create a builder with a shallow copy of this instance. */
    public DocumentConfigBase.Builder toBuilder() {
        return new DocumentConfigBase.Builder().type(getType());
    }
}
