/*
 * Definancy API
 * REST API for managing asset, network and contract configurations, and vault-based financial operations. This API provides a comprehensive set of endpoints for health monitoring, network management, asset  configuration, contract management, vault lifecycle management, and QR-Code generation. It is designed to facilitate seamless integration with financial systems, ensuring secure and efficient payment  processing while maintaining strict compliance standards.
 *
 * The version of the OpenAPI document: 0.0.1.wip.20250925
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.definancy.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.util.Objects;
import java.util.StringJoiner;

/** DocumentConfig */
@JsonPropertyOrder({DocumentConfig.JSON_PROPERTY_TYPE, DocumentConfig.JSON_PROPERTY_DATA})
@javax.annotation.Generated(
        value = "org.openapitools.codegen.languages.JavaClientCodegen",
        comments = "Generator version: 7.20.0")
@JsonIgnoreProperties(
        value = "type", // ignore manually set type, it will be automatically generated by Jackson
        // during serialization
        allowSetters = true // allows the type to be set during deserialization
        )
@JsonTypeInfo(
        use = JsonTypeInfo.Id.NAME,
        include = JsonTypeInfo.As.PROPERTY,
        property = "type",
        visible = true)
@JsonSubTypes({
    @JsonSubTypes.Type(value = DocumentConfigCustodialV1.class, name = "CustodialV1"),
    @JsonSubTypes.Type(value = DocumentConfigNonCustodialV1.class, name = "NonCustodialV1"),
    @JsonSubTypes.Type(value = DocumentConfigPersonV1.class, name = "PersonV1"),
})
public class DocumentConfig {
    public static final String JSON_PROPERTY_TYPE = "type";
    // The discriminator does not have Nullability-annotation since it is added during serialization
    // by the @JsonTypeName annotation
    private DocumentType type;

    public static final String JSON_PROPERTY_DATA = "data";
    @javax.annotation.Nonnull private NonCustodialV1 data;

    public DocumentConfig() {}

    /** Constructor with all args parameters */
    public DocumentConfig(
            @JsonProperty(value = JSON_PROPERTY_TYPE, required = true) DocumentType type,
            @JsonProperty(value = JSON_PROPERTY_DATA, required = true) NonCustodialV1 data) {
        this.type = type;
        this.data = data;
    }

    public DocumentConfig type(@javax.annotation.Nonnull DocumentType type) {

        this.type = type;
        return this;
    }

    /**
     * Get type
     *
     * @return type
     */
    @javax.annotation.Nonnull
    @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public DocumentType getType() {
        return type;
    }

    @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setType(@javax.annotation.Nonnull DocumentType type) {
        this.type = type;
    }

    public DocumentConfig data(@javax.annotation.Nonnull NonCustodialV1 data) {

        this.data = data;
        return this;
    }

    /**
     * Get data
     *
     * @return data
     */
    @javax.annotation.Nonnull
    @JsonProperty(value = JSON_PROPERTY_DATA, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public NonCustodialV1 getData() {
        return data;
    }

    @JsonProperty(value = JSON_PROPERTY_DATA, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setData(@javax.annotation.Nonnull NonCustodialV1 data) {
        this.data = data;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        DocumentConfig documentConfig = (DocumentConfig) o;
        return Objects.equals(this.type, documentConfig.type)
                && Objects.equals(this.data, documentConfig.data);
    }

    @Override
    public int hashCode() {
        return Objects.hash(type, data);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class DocumentConfig {\n");
        sb.append("    type: ").append(toIndentedString(type)).append("\n");
        sb.append("    data: ").append(toIndentedString(data)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces (except the first
     * line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    /**
     * Convert the instance into URL query string.
     *
     * @return URL query string
     */
    public String toUrlQueryString() {
        return toUrlQueryString(null);
    }

    /**
     * Convert the instance into URL query string.
     *
     * @param prefix prefix of the query string
     * @return URL query string
     */
    public String toUrlQueryString(String prefix) {
        String suffix = "";
        String containerSuffix = "";
        String containerPrefix = "";
        if (prefix == null) {
            // style=form, explode=true, e.g. /pet?name=cat&type=manx
            prefix = "";
        } else {
            // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
            prefix = prefix + "[";
            suffix = "]";
            containerSuffix = "]";
            containerPrefix = "[";
        }

        StringJoiner joiner = new StringJoiner("&");

        // add `type` to the URL query string
        if (getType() != null) {
            try {
                joiner.add(
                        String.format(
                                java.util.Locale.ROOT,
                                "%stype%s=%s",
                                prefix,
                                suffix,
                                URLEncoder.encode(String.valueOf(getType()), "UTF-8")
                                        .replaceAll("\\+", "%20")));
            } catch (UnsupportedEncodingException e) {
                // Should never happen, UTF-8 is always supported
                throw new RuntimeException(e);
            }
        }

        // add `data` to the URL query string
        if (getData() != null) {
            joiner.add(getData().toUrlQueryString(prefix + "data" + suffix));
        }

        return joiner.toString();
    }

    public static class Builder {

        private DocumentConfig instance;

        public Builder() {
            this(new DocumentConfig());
        }

        protected Builder(DocumentConfig instance) {
            this.instance = instance;
        }

        public DocumentConfig.Builder type(DocumentType type) {
            this.instance.type = type;
            return this;
        }

        public DocumentConfig.Builder data(NonCustodialV1 data) {
            this.instance.data = data;
            return this;
        }

        /**
         * returns a built DocumentConfig instance.
         *
         * <p>The builder is not reusable.
         */
        public DocumentConfig build() {
            try {
                return this.instance;
            } finally {
                // ensure that this.instance is not reused
                this.instance = null;
            }
        }

        @Override
        public String toString() {
            return getClass() + "=(" + instance + ")";
        }
    }

    /** Create a builder with no initialized field. */
    public static DocumentConfig.Builder builder() {
        return new DocumentConfig.Builder();
    }

    /** Create a builder with a shallow copy of this instance. */
    public DocumentConfig.Builder toBuilder() {
        return new DocumentConfig.Builder().type(getType()).data(getData());
    }
}
