/*
 * Definancy API
 * Specification version: 0.0.1.wip.20250924
 *
 * NOTE: This class is auto generated by our custom generator.
 * Do not edit the class manually.
 */


package com.definancy.model;

import java.util.Objects;
import java.util.Locale;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import java.util.Locale;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Document validation status category.
 */
@JsonAdapter(DocumentStatusId.Adapter.class)
public enum DocumentStatusId {
  
  PENDING("pending"),
  
  EXPIRED("expired"),
  
  ACCEPTED("accepted"),
  
  REJECTED("rejected"),
  
  ARCHIVED("archived");

  private String value;

  DocumentStatusId(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static DocumentStatusId fromValue(String value) {
    for (DocumentStatusId b : DocumentStatusId.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<DocumentStatusId> {
    @Override
    public void write(final JsonWriter jsonWriter, final DocumentStatusId enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public DocumentStatusId read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return DocumentStatusId.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    DocumentStatusId.fromValue(value);
  }
}

