/*
 * Definancy API
 * Specification version: 0.0.1.wip.20250925
 *
 * NOTE: This class is auto generated by our custom generator.
 * Do not edit the class manually.
 */


package com.definancy.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.definancy.JSON;


/**
 * Expire
 */
@JsonPropertyOrder({
  Expire.JSON_PROPERTY_AT,
  Expire.JSON_PROPERTY_IN
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.16.0-SNAPSHOT")
public class Expire {
  public static final String JSON_PROPERTY_AT = "at";
  @javax.annotation.Nonnull
  private Integer at;

  public static final String JSON_PROPERTY_IN = "in";
  @javax.annotation.Nonnull
  private Integer in;

  public Expire() { 
  }

  public Expire at(@javax.annotation.Nonnull Integer at) {
    this.at = at;
    return this;
  }

  /**
   * UNIX timestamp in milliseconds representing a specific point in time. Used for tracking creation dates, expiration times, transaction timestamps, and other time-sensitive operations throughout the payment lifecycle.
   * minimum: 0
   * @return at
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_AT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getAt() {
    return at;
  }


  @JsonProperty(value = JSON_PROPERTY_AT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAt(@javax.annotation.Nonnull Integer at) {
    this.at = at;
  }


  public Expire in(@javax.annotation.Nonnull Integer in) {
    this.in = in;
    return this;
  }

  /**
   * Time in milliseconds representing an amount of time. Used for expiration cut-offs, and other time-sensitive operations throughout  the payment lifecycle.
   * minimum: 0
   * @return in
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_IN, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getIn() {
    return in;
  }


  @JsonProperty(value = JSON_PROPERTY_IN, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setIn(@javax.annotation.Nonnull Integer in) {
    this.in = in;
  }


  /**
   * Return true if this Expire object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Expire expire = (Expire) o;
    return Objects.equals(this.at, expire.at) &&
        Objects.equals(this.in, expire.in);
  }

  @Override
  public int hashCode() {
    return Objects.hash(at, in);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Expire {\n");
    sb.append("    at: ").append(toIndentedString(at)).append("\n");
    sb.append("    in: ").append(toIndentedString(in)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

