/*
 * Definancy API
 * REST API for managing asset, network and contract configurations, and vault-based financial operations. This API provides a comprehensive set of endpoints for health monitoring, network management, asset  configuration, contract management, vault lifecycle management, and QR-Code generation. It is designed to facilitate seamless integration with financial systems, ensuring secure and efficient payment  processing while maintaining strict compliance standards.
 *
 * The version of the OpenAPI document: 0.0.1.wip.20250925
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.definancy.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import java.util.Objects;
import java.util.StringJoiner;

/** NetworkMediaMap */
@JsonPropertyOrder({
    NetworkMediaMap.JSON_PROPERTY_LOGO_LIGHT,
    NetworkMediaMap.JSON_PROPERTY_LOGO_DARK
})
@javax.annotation.Generated(
        value = "org.openapitools.codegen.languages.JavaClientCodegen",
        comments = "Generator version: 7.20.0")
public class NetworkMediaMap {
    public static final String JSON_PROPERTY_LOGO_LIGHT = "logo-light";
    @javax.annotation.Nonnull private Media logoLight;

    public static final String JSON_PROPERTY_LOGO_DARK = "logo-dark";
    @javax.annotation.Nonnull private Media logoDark;

    public NetworkMediaMap() {}

    /** Constructor with all args parameters */
    public NetworkMediaMap(
            @JsonProperty(value = JSON_PROPERTY_LOGO_LIGHT, required = true) Media logoLight,
            @JsonProperty(value = JSON_PROPERTY_LOGO_DARK, required = true) Media logoDark) {
        this.logoLight = logoLight;
        this.logoDark = logoDark;
    }

    public NetworkMediaMap logoLight(@javax.annotation.Nonnull Media logoLight) {

        this.logoLight = logoLight;
        return this;
    }

    /**
     * Get logoLight
     *
     * @return logoLight
     */
    @javax.annotation.Nonnull
    @JsonProperty(value = JSON_PROPERTY_LOGO_LIGHT, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public Media getLogoLight() {
        return logoLight;
    }

    @JsonProperty(value = JSON_PROPERTY_LOGO_LIGHT, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setLogoLight(@javax.annotation.Nonnull Media logoLight) {
        this.logoLight = logoLight;
    }

    public NetworkMediaMap logoDark(@javax.annotation.Nonnull Media logoDark) {

        this.logoDark = logoDark;
        return this;
    }

    /**
     * Get logoDark
     *
     * @return logoDark
     */
    @javax.annotation.Nonnull
    @JsonProperty(value = JSON_PROPERTY_LOGO_DARK, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public Media getLogoDark() {
        return logoDark;
    }

    @JsonProperty(value = JSON_PROPERTY_LOGO_DARK, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setLogoDark(@javax.annotation.Nonnull Media logoDark) {
        this.logoDark = logoDark;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        NetworkMediaMap networkMediaMap = (NetworkMediaMap) o;
        return Objects.equals(this.logoLight, networkMediaMap.logoLight)
                && Objects.equals(this.logoDark, networkMediaMap.logoDark);
    }

    @Override
    public int hashCode() {
        return Objects.hash(logoLight, logoDark);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class NetworkMediaMap {\n");
        sb.append("    logoLight: ").append(toIndentedString(logoLight)).append("\n");
        sb.append("    logoDark: ").append(toIndentedString(logoDark)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces (except the first
     * line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    /**
     * Convert the instance into URL query string.
     *
     * @return URL query string
     */
    public String toUrlQueryString() {
        return toUrlQueryString(null);
    }

    /**
     * Convert the instance into URL query string.
     *
     * @param prefix prefix of the query string
     * @return URL query string
     */
    public String toUrlQueryString(String prefix) {
        String suffix = "";
        String containerSuffix = "";
        String containerPrefix = "";
        if (prefix == null) {
            // style=form, explode=true, e.g. /pet?name=cat&type=manx
            prefix = "";
        } else {
            // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
            prefix = prefix + "[";
            suffix = "]";
            containerSuffix = "]";
            containerPrefix = "[";
        }

        StringJoiner joiner = new StringJoiner("&");

        // add `logo-light` to the URL query string
        if (getLogoLight() != null) {
            joiner.add(getLogoLight().toUrlQueryString(prefix + "logo-light" + suffix));
        }

        // add `logo-dark` to the URL query string
        if (getLogoDark() != null) {
            joiner.add(getLogoDark().toUrlQueryString(prefix + "logo-dark" + suffix));
        }

        return joiner.toString();
    }

    public static class Builder {

        private NetworkMediaMap instance;

        public Builder() {
            this(new NetworkMediaMap());
        }

        protected Builder(NetworkMediaMap instance) {
            this.instance = instance;
        }

        public NetworkMediaMap.Builder logoLight(Media logoLight) {
            this.instance.logoLight = logoLight;
            return this;
        }

        public NetworkMediaMap.Builder logoDark(Media logoDark) {
            this.instance.logoDark = logoDark;
            return this;
        }

        /**
         * returns a built NetworkMediaMap instance.
         *
         * <p>The builder is not reusable.
         */
        public NetworkMediaMap build() {
            try {
                return this.instance;
            } finally {
                // ensure that this.instance is not reused
                this.instance = null;
            }
        }

        @Override
        public String toString() {
            return getClass() + "=(" + instance + ")";
        }
    }

    /** Create a builder with no initialized field. */
    public static NetworkMediaMap.Builder builder() {
        return new NetworkMediaMap.Builder();
    }

    /** Create a builder with a shallow copy of this instance. */
    public NetworkMediaMap.Builder toBuilder() {
        return new NetworkMediaMap.Builder().logoLight(getLogoLight()).logoDark(getLogoDark());
    }
}
