/*
 * Definancy API
 * Specification version: 0.0.1.wip.20250925
 *
 * NOTE: This class is auto generated by our custom generator.
 * Do not edit the class manually.
 */


package com.definancy.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.definancy.JSON;


import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Locale;

/**
 * Payment acceptance processing state categories representing different  stages in the payment lifecycle from compliance verification through  final confirmation or cancellation.
 */
public enum PaymentAcceptanceStatusId {
  
  COMPLIANCE("compliance"),
  
  WAITING("waiting"),
  
  CONFIRMING("confirming"),
  
  CONFIRMED("confirmed"),
  
  EXPIRED("expired"),
  
  CANCELLED("cancelled"),
  
  UNKNOWN_DEFAULT_OPEN_API("unknown_default_open_api");

  private String value;

  PaymentAcceptanceStatusId(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static PaymentAcceptanceStatusId fromValue(String value) {
    for (PaymentAcceptanceStatusId b : PaymentAcceptanceStatusId.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    return UNKNOWN_DEFAULT_OPEN_API;
  }
}

