/*
 * Definancy API
 * REST API for managing asset, network and contract configurations, and vault-based financial operations. This API provides a comprehensive set of endpoints for health monitoring, network management, asset  configuration, contract management, vault lifecycle management, and QR-Code generation. It is designed to facilitate seamless integration with financial systems, ensuring secure and efficient payment  processing while maintaining strict compliance standards.
 *
 * The version of the OpenAPI document: 0.0.1.wip.20250925
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.definancy.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.util.Objects;
import java.util.StringJoiner;
import java.util.UUID;

/**
 * Complete payment acceptance record managing the full lifecycle of payment processing from
 * initiation through completion. Combines configuration, operational state, and compliance tracking
 * for comprehensive payment management.
 */
@JsonPropertyOrder({
    PaymentAcceptance.JSON_PROPERTY_ID,
    PaymentAcceptance.JSON_PROPERTY_INFO,
    PaymentAcceptance.JSON_PROPERTY_CONFIG
})
@javax.annotation.Generated(
        value = "org.openapitools.codegen.languages.JavaClientCodegen",
        comments = "Generator version: 7.20.0")
public class PaymentAcceptance {
    public static final String JSON_PROPERTY_ID = "id";
    @javax.annotation.Nonnull private UUID id;

    public static final String JSON_PROPERTY_INFO = "info";
    @javax.annotation.Nonnull private PaymentAcceptanceInfo info;

    public static final String JSON_PROPERTY_CONFIG = "config";
    @javax.annotation.Nonnull private PaymentAcceptanceConfig config;

    public PaymentAcceptance() {}

    /** Constructor with all args parameters */
    public PaymentAcceptance(
            @JsonProperty(value = JSON_PROPERTY_ID, required = true) UUID id,
            @JsonProperty(value = JSON_PROPERTY_INFO, required = true) PaymentAcceptanceInfo info,
            @JsonProperty(value = JSON_PROPERTY_CONFIG, required = true)
                    PaymentAcceptanceConfig config) {
        this.id = id;
        this.info = info;
        this.config = config;
    }

    public PaymentAcceptance id(@javax.annotation.Nonnull UUID id) {

        this.id = id;
        return this;
    }

    /**
     * Universally unique identifier used for resources that require globally unique identification.
     * Provides 128-bit uniqueness suitable for distributed systems and cross-system integration.
     *
     * @return id
     */
    @javax.annotation.Nonnull
    @JsonProperty(value = JSON_PROPERTY_ID, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public UUID getId() {
        return id;
    }

    @JsonProperty(value = JSON_PROPERTY_ID, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setId(@javax.annotation.Nonnull UUID id) {
        this.id = id;
    }

    public PaymentAcceptance info(@javax.annotation.Nonnull PaymentAcceptanceInfo info) {

        this.info = info;
        return this;
    }

    /**
     * Get info
     *
     * @return info
     */
    @javax.annotation.Nonnull
    @JsonProperty(value = JSON_PROPERTY_INFO, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public PaymentAcceptanceInfo getInfo() {
        return info;
    }

    @JsonProperty(value = JSON_PROPERTY_INFO, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setInfo(@javax.annotation.Nonnull PaymentAcceptanceInfo info) {
        this.info = info;
    }

    public PaymentAcceptance config(@javax.annotation.Nonnull PaymentAcceptanceConfig config) {

        this.config = config;
        return this;
    }

    /**
     * Get config
     *
     * @return config
     */
    @javax.annotation.Nonnull
    @JsonProperty(value = JSON_PROPERTY_CONFIG, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public PaymentAcceptanceConfig getConfig() {
        return config;
    }

    @JsonProperty(value = JSON_PROPERTY_CONFIG, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setConfig(@javax.annotation.Nonnull PaymentAcceptanceConfig config) {
        this.config = config;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        PaymentAcceptance paymentAcceptance = (PaymentAcceptance) o;
        return Objects.equals(this.id, paymentAcceptance.id)
                && Objects.equals(this.info, paymentAcceptance.info)
                && Objects.equals(this.config, paymentAcceptance.config);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, info, config);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class PaymentAcceptance {\n");
        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    info: ").append(toIndentedString(info)).append("\n");
        sb.append("    config: ").append(toIndentedString(config)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces (except the first
     * line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    /**
     * Convert the instance into URL query string.
     *
     * @return URL query string
     */
    public String toUrlQueryString() {
        return toUrlQueryString(null);
    }

    /**
     * Convert the instance into URL query string.
     *
     * @param prefix prefix of the query string
     * @return URL query string
     */
    public String toUrlQueryString(String prefix) {
        String suffix = "";
        String containerSuffix = "";
        String containerPrefix = "";
        if (prefix == null) {
            // style=form, explode=true, e.g. /pet?name=cat&type=manx
            prefix = "";
        } else {
            // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
            prefix = prefix + "[";
            suffix = "]";
            containerSuffix = "]";
            containerPrefix = "[";
        }

        StringJoiner joiner = new StringJoiner("&");

        // add `id` to the URL query string
        if (getId() != null) {
            try {
                joiner.add(
                        String.format(
                                java.util.Locale.ROOT,
                                "%sid%s=%s",
                                prefix,
                                suffix,
                                URLEncoder.encode(String.valueOf(getId()), "UTF-8")
                                        .replaceAll("\\+", "%20")));
            } catch (UnsupportedEncodingException e) {
                // Should never happen, UTF-8 is always supported
                throw new RuntimeException(e);
            }
        }

        // add `info` to the URL query string
        if (getInfo() != null) {
            joiner.add(getInfo().toUrlQueryString(prefix + "info" + suffix));
        }

        // add `config` to the URL query string
        if (getConfig() != null) {
            joiner.add(getConfig().toUrlQueryString(prefix + "config" + suffix));
        }

        return joiner.toString();
    }

    public static class Builder {

        private PaymentAcceptance instance;

        public Builder() {
            this(new PaymentAcceptance());
        }

        protected Builder(PaymentAcceptance instance) {
            this.instance = instance;
        }

        public PaymentAcceptance.Builder id(UUID id) {
            this.instance.id = id;
            return this;
        }

        public PaymentAcceptance.Builder info(PaymentAcceptanceInfo info) {
            this.instance.info = info;
            return this;
        }

        public PaymentAcceptance.Builder config(PaymentAcceptanceConfig config) {
            this.instance.config = config;
            return this;
        }

        /**
         * returns a built PaymentAcceptance instance.
         *
         * <p>The builder is not reusable.
         */
        public PaymentAcceptance build() {
            try {
                return this.instance;
            } finally {
                // ensure that this.instance is not reused
                this.instance = null;
            }
        }

        @Override
        public String toString() {
            return getClass() + "=(" + instance + ")";
        }
    }

    /** Create a builder with no initialized field. */
    public static PaymentAcceptance.Builder builder() {
        return new PaymentAcceptance.Builder();
    }

    /** Create a builder with a shallow copy of this instance. */
    public PaymentAcceptance.Builder toBuilder() {
        return new PaymentAcceptance.Builder().id(getId()).info(getInfo()).config(getConfig());
    }
}
