/*
 * Definancy API
 * Specification version: 0.0.1.wip.20250925
 *
 * NOTE: This class is auto generated by our custom generator.
 * Do not edit the class manually.
 */


package com.definancy.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import java.util.Locale;
import com.definancy.model.ContractAmount;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.definancy.JSON;


/**
 * Individual payment calculation scenario showing the relationship between requested amounts and actual payment requirements including fees, conversions, and network-specific adjustments.
 */
@JsonPropertyOrder({
  PaymentEstimateScenario.JSON_PROPERTY_PRICE,
  PaymentEstimateScenario.JSON_PROPERTY_PAY
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.16.0-SNAPSHOT")
public class PaymentEstimateScenario {
  public static final String JSON_PROPERTY_PRICE = "price";
  @javax.annotation.Nonnull
  private ContractAmount price;

  public static final String JSON_PROPERTY_PAY = "pay";
  @javax.annotation.Nonnull
  private ContractAmount pay;

  public PaymentEstimateScenario() { 
  }

  public PaymentEstimateScenario price(@javax.annotation.Nonnull ContractAmount price) {
    this.price = price;
    return this;
  }

  /**
   * Get price
   * @return price
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_PRICE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ContractAmount getPrice() {
    return price;
  }


  @JsonProperty(value = JSON_PROPERTY_PRICE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPrice(@javax.annotation.Nonnull ContractAmount price) {
    this.price = price;
  }


  public PaymentEstimateScenario pay(@javax.annotation.Nonnull ContractAmount pay) {
    this.pay = pay;
    return this;
  }

  /**
   * Get pay
   * @return pay
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_PAY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ContractAmount getPay() {
    return pay;
  }


  @JsonProperty(value = JSON_PROPERTY_PAY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPay(@javax.annotation.Nonnull ContractAmount pay) {
    this.pay = pay;
  }


  /**
   * Return true if this PaymentEstimateScenario object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PaymentEstimateScenario paymentEstimateScenario = (PaymentEstimateScenario) o;
    return Objects.equals(this.price, paymentEstimateScenario.price) &&
        Objects.equals(this.pay, paymentEstimateScenario.pay);
  }

  @Override
  public int hashCode() {
    return Objects.hash(price, pay);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PaymentEstimateScenario {\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    pay: ").append(toIndentedString(pay)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

