/*
 * Definancy API
 * REST API for managing asset, network and contract configurations, and vault-based financial operations. This API provides a comprehensive set of endpoints for health monitoring, network management, asset  configuration, contract management, vault lifecycle management, and QR-Code generation. It is designed to facilitate seamless integration with financial systems, ensuring secure and efficient payment  processing while maintaining strict compliance standards.
 *
 * The version of the OpenAPI document: 0.0.1.wip.20250925
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.definancy.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.StringJoiner;

/**
 * Payment acceptance operational state and lifecycle information. Contains current processing
 * status, payment scenarios, compliance state, and version tracking for audit and monitoring
 * purposes.
 */
@JsonPropertyOrder({
    PaymentAcceptanceInfo.JSON_PROPERTY_STATUS,
    PaymentAcceptanceInfo.JSON_PROPERTY_VERSION,
    PaymentAcceptanceInfo.JSON_PROPERTY_SCENARIOS,
    PaymentAcceptanceInfo.JSON_PROPERTY_COMPLIANCE
})
@javax.annotation.Generated(
        value = "org.openapitools.codegen.languages.JavaClientCodegen",
        comments = "Generator version: 7.20.0")
public class PaymentAcceptanceInfo {
    public static final String JSON_PROPERTY_STATUS = "status";
    @javax.annotation.Nonnull private PaymentAcceptanceStatus status;

    public static final String JSON_PROPERTY_VERSION = "version";
    @javax.annotation.Nonnull private Version version;

    public static final String JSON_PROPERTY_SCENARIOS = "scenarios";
    @javax.annotation.Nonnull private List<PaymentAcceptanceScenario> scenarios;

    public static final String JSON_PROPERTY_COMPLIANCE = "compliance";
    @javax.annotation.Nonnull private Compliance compliance;

    public PaymentAcceptanceInfo() {}

    /** Constructor with all args parameters */
    public PaymentAcceptanceInfo(
            @JsonProperty(value = JSON_PROPERTY_STATUS, required = true)
                    PaymentAcceptanceStatus status,
            @JsonProperty(value = JSON_PROPERTY_VERSION, required = true) Version version,
            @JsonProperty(value = JSON_PROPERTY_SCENARIOS, required = true)
                    List<PaymentAcceptanceScenario> scenarios,
            @JsonProperty(value = JSON_PROPERTY_COMPLIANCE, required = true)
                    Compliance compliance) {
        this.status = status;
        this.version = version;
        this.scenarios = scenarios;
        this.compliance = compliance;
    }

    public PaymentAcceptanceInfo status(@javax.annotation.Nonnull PaymentAcceptanceStatus status) {

        this.status = status;
        return this;
    }

    /**
     * Get status
     *
     * @return status
     */
    @javax.annotation.Nonnull
    @JsonProperty(value = JSON_PROPERTY_STATUS, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public PaymentAcceptanceStatus getStatus() {
        return status;
    }

    @JsonProperty(value = JSON_PROPERTY_STATUS, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setStatus(@javax.annotation.Nonnull PaymentAcceptanceStatus status) {
        this.status = status;
    }

    public PaymentAcceptanceInfo version(@javax.annotation.Nonnull Version version) {

        this.version = version;
        return this;
    }

    /**
     * Get version
     *
     * @return version
     */
    @javax.annotation.Nonnull
    @JsonProperty(value = JSON_PROPERTY_VERSION, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public Version getVersion() {
        return version;
    }

    @JsonProperty(value = JSON_PROPERTY_VERSION, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setVersion(@javax.annotation.Nonnull Version version) {
        this.version = version;
    }

    public PaymentAcceptanceInfo scenarios(
            @javax.annotation.Nonnull List<PaymentAcceptanceScenario> scenarios) {

        this.scenarios = scenarios;
        return this;
    }

    public PaymentAcceptanceInfo addScenariosItem(PaymentAcceptanceScenario scenariosItem) {
        if (this.scenarios == null) {
            this.scenarios = new ArrayList<>();
        }
        this.scenarios.add(scenariosItem);
        return this;
    }

    /**
     * Active payment execution scenarios with blockchain addresses, amounts, and transaction
     * tracking information.
     *
     * @return scenarios
     */
    @javax.annotation.Nonnull
    @JsonProperty(value = JSON_PROPERTY_SCENARIOS, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public List<PaymentAcceptanceScenario> getScenarios() {
        return scenarios;
    }

    @JsonProperty(value = JSON_PROPERTY_SCENARIOS, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setScenarios(@javax.annotation.Nonnull List<PaymentAcceptanceScenario> scenarios) {
        this.scenarios = scenarios;
    }

    public PaymentAcceptanceInfo compliance(@javax.annotation.Nonnull Compliance compliance) {

        this.compliance = compliance;
        return this;
    }

    /**
     * Get compliance
     *
     * @return compliance
     */
    @javax.annotation.Nonnull
    @JsonProperty(value = JSON_PROPERTY_COMPLIANCE, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public Compliance getCompliance() {
        return compliance;
    }

    @JsonProperty(value = JSON_PROPERTY_COMPLIANCE, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setCompliance(@javax.annotation.Nonnull Compliance compliance) {
        this.compliance = compliance;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        PaymentAcceptanceInfo paymentAcceptanceInfo = (PaymentAcceptanceInfo) o;
        return Objects.equals(this.status, paymentAcceptanceInfo.status)
                && Objects.equals(this.version, paymentAcceptanceInfo.version)
                && Objects.equals(this.scenarios, paymentAcceptanceInfo.scenarios)
                && Objects.equals(this.compliance, paymentAcceptanceInfo.compliance);
    }

    @Override
    public int hashCode() {
        return Objects.hash(status, version, scenarios, compliance);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class PaymentAcceptanceInfo {\n");
        sb.append("    status: ").append(toIndentedString(status)).append("\n");
        sb.append("    version: ").append(toIndentedString(version)).append("\n");
        sb.append("    scenarios: ").append(toIndentedString(scenarios)).append("\n");
        sb.append("    compliance: ").append(toIndentedString(compliance)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces (except the first
     * line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    /**
     * Convert the instance into URL query string.
     *
     * @return URL query string
     */
    public String toUrlQueryString() {
        return toUrlQueryString(null);
    }

    /**
     * Convert the instance into URL query string.
     *
     * @param prefix prefix of the query string
     * @return URL query string
     */
    public String toUrlQueryString(String prefix) {
        String suffix = "";
        String containerSuffix = "";
        String containerPrefix = "";
        if (prefix == null) {
            // style=form, explode=true, e.g. /pet?name=cat&type=manx
            prefix = "";
        } else {
            // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
            prefix = prefix + "[";
            suffix = "]";
            containerSuffix = "]";
            containerPrefix = "[";
        }

        StringJoiner joiner = new StringJoiner("&");

        // add `status` to the URL query string
        if (getStatus() != null) {
            joiner.add(getStatus().toUrlQueryString(prefix + "status" + suffix));
        }

        // add `version` to the URL query string
        if (getVersion() != null) {
            joiner.add(getVersion().toUrlQueryString(prefix + "version" + suffix));
        }

        // add `scenarios` to the URL query string
        if (getScenarios() != null) {
            for (int i = 0; i < getScenarios().size(); i++) {
                if (getScenarios().get(i) != null) {
                    joiner.add(
                            getScenarios()
                                    .get(i)
                                    .toUrlQueryString(
                                            String.format(
                                                    java.util.Locale.ROOT,
                                                    "%sscenarios%s%s",
                                                    prefix,
                                                    suffix,
                                                    "".equals(suffix)
                                                            ? ""
                                                            : String.format(
                                                                    java.util.Locale.ROOT,
                                                                    "%s%d%s",
                                                                    containerPrefix,
                                                                    i,
                                                                    containerSuffix))));
                }
            }
        }

        // add `compliance` to the URL query string
        if (getCompliance() != null) {
            joiner.add(getCompliance().toUrlQueryString(prefix + "compliance" + suffix));
        }

        return joiner.toString();
    }

    public static class Builder {

        private PaymentAcceptanceInfo instance;

        public Builder() {
            this(new PaymentAcceptanceInfo());
        }

        protected Builder(PaymentAcceptanceInfo instance) {
            this.instance = instance;
        }

        public PaymentAcceptanceInfo.Builder status(PaymentAcceptanceStatus status) {
            this.instance.status = status;
            return this;
        }

        public PaymentAcceptanceInfo.Builder version(Version version) {
            this.instance.version = version;
            return this;
        }

        public PaymentAcceptanceInfo.Builder scenarios(List<PaymentAcceptanceScenario> scenarios) {
            this.instance.scenarios = scenarios;
            return this;
        }

        public PaymentAcceptanceInfo.Builder compliance(Compliance compliance) {
            this.instance.compliance = compliance;
            return this;
        }

        /**
         * returns a built PaymentAcceptanceInfo instance.
         *
         * <p>The builder is not reusable.
         */
        public PaymentAcceptanceInfo build() {
            try {
                return this.instance;
            } finally {
                // ensure that this.instance is not reused
                this.instance = null;
            }
        }

        @Override
        public String toString() {
            return getClass() + "=(" + instance + ")";
        }
    }

    /** Create a builder with no initialized field. */
    public static PaymentAcceptanceInfo.Builder builder() {
        return new PaymentAcceptanceInfo.Builder();
    }

    /** Create a builder with a shallow copy of this instance. */
    public PaymentAcceptanceInfo.Builder toBuilder() {
        return new PaymentAcceptanceInfo.Builder()
                .status(getStatus())
                .version(getVersion())
                .scenarios(getScenarios())
                .compliance(getCompliance());
    }
}
