/*
 * Definancy API
 * Specification version: 0.0.1.wip.20250925
 *
 * NOTE: This class is auto generated by our custom generator.
 * Do not edit the class manually.
 */


package com.definancy.model;

import java.util.Objects;
import java.util.Locale;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import java.util.Locale;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Type of business identification document accepted for legal entity  verification. Currently limited to tax identification documents  but may be expanded to include other business registration types.
 */
@JsonAdapter(PersonLegalIdType.Adapter.class)
public enum PersonLegalIdType {
  
  TAX_ID("TaxId"),
  
  UNKNOWN_DEFAULT_OPEN_API("unknown_default_open_api");

  private String value;

  PersonLegalIdType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static PersonLegalIdType fromValue(String value) {
    for (PersonLegalIdType b : PersonLegalIdType.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    return UNKNOWN_DEFAULT_OPEN_API;
  }

  public static class Adapter extends TypeAdapter<PersonLegalIdType> {
    @Override
    public void write(final JsonWriter jsonWriter, final PersonLegalIdType enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public PersonLegalIdType read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return PersonLegalIdType.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    PersonLegalIdType.fromValue(value);
  }
}

