/*
 * Definancy API
 * REST API for managing asset, network and contract configurations, and vault-based financial operations. This API provides a comprehensive set of endpoints for health monitoring, network management, asset  configuration, contract management, vault lifecycle management, and QR-Code generation. It is designed to facilitate seamless integration with financial systems, ensuring secure and efficient payment  processing while maintaining strict compliance standards.
 *
 * The version of the OpenAPI document: 0.0.1.wip.20250925
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.definancy.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.util.Objects;
import java.util.StringJoiner;

/**
 * Complete physical address information used for identity verification and compliance
 * documentation. Includes all components necessary for address validation and geographic
 * identification.
 */
@JsonPropertyOrder({
    PersonAddress.JSON_PROPERTY_STREET,
    PersonAddress.JSON_PROPERTY_POSTAL_CODE,
    PersonAddress.JSON_PROPERTY_REGION,
    PersonAddress.JSON_PROPERTY_COUNTRY
})
@javax.annotation.Generated(
        value = "org.openapitools.codegen.languages.JavaClientCodegen",
        comments = "Generator version: 7.20.0")
public class PersonAddress {
    public static final String JSON_PROPERTY_STREET = "street";
    @javax.annotation.Nonnull private String street;

    public static final String JSON_PROPERTY_POSTAL_CODE = "postal-code";
    @javax.annotation.Nonnull private String postalCode;

    public static final String JSON_PROPERTY_REGION = "region";
    @javax.annotation.Nonnull private String region;

    public static final String JSON_PROPERTY_COUNTRY = "country";
    @javax.annotation.Nonnull private String country;

    public PersonAddress() {}

    /** Constructor with all args parameters */
    public PersonAddress(
            @JsonProperty(value = JSON_PROPERTY_STREET, required = true) String street,
            @JsonProperty(value = JSON_PROPERTY_POSTAL_CODE, required = true) String postalCode,
            @JsonProperty(value = JSON_PROPERTY_REGION, required = true) String region,
            @JsonProperty(value = JSON_PROPERTY_COUNTRY, required = true) String country) {
        this.street = street;
        this.postalCode = postalCode;
        this.region = region;
        this.country = country;
    }

    public PersonAddress street(@javax.annotation.Nonnull String street) {

        this.street = street;
        return this;
    }

    /**
     * Complete street address including building number, street name, apartment or suite
     * information. Used in compliance documents for physical address verification and identity
     * confirmation processes.
     *
     * @return street
     */
    @javax.annotation.Nonnull
    @JsonProperty(value = JSON_PROPERTY_STREET, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public String getStreet() {
        return street;
    }

    @JsonProperty(value = JSON_PROPERTY_STREET, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setStreet(@javax.annotation.Nonnull String street) {
        this.street = street;
    }

    public PersonAddress postalCode(@javax.annotation.Nonnull String postalCode) {

        this.postalCode = postalCode;
        return this;
    }

    /**
     * Geographic postal or ZIP code for address verification. Format varies by country (e.g.,
     * 5-digit ZIP codes in US, alphanumeric postal codes in Canada). Used for compliance and
     * identity verification.
     *
     * @return postalCode
     */
    @javax.annotation.Nonnull
    @JsonProperty(value = JSON_PROPERTY_POSTAL_CODE, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public String getPostalCode() {
        return postalCode;
    }

    @JsonProperty(value = JSON_PROPERTY_POSTAL_CODE, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setPostalCode(@javax.annotation.Nonnull String postalCode) {
        this.postalCode = postalCode;
    }

    public PersonAddress region(@javax.annotation.Nonnull String region) {

        this.region = region;
        return this;
    }

    /**
     * Administrative subdivision such as state, province, prefecture, or region. Used in address
     * information for compliance documents and geographic identification in identity verification
     * processes.
     *
     * @return region
     */
    @javax.annotation.Nonnull
    @JsonProperty(value = JSON_PROPERTY_REGION, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public String getRegion() {
        return region;
    }

    @JsonProperty(value = JSON_PROPERTY_REGION, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setRegion(@javax.annotation.Nonnull String region) {
        this.region = region;
    }

    public PersonAddress country(@javax.annotation.Nonnull String country) {

        this.country = country;
        return this;
    }

    /**
     * Country name or ISO 3166-1 alpha-2 country code for geographic identification. Used in
     * address information, birth records, and incorporation details for compliance and identity
     * verification purposes.
     *
     * @return country
     */
    @javax.annotation.Nonnull
    @JsonProperty(value = JSON_PROPERTY_COUNTRY, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public String getCountry() {
        return country;
    }

    @JsonProperty(value = JSON_PROPERTY_COUNTRY, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setCountry(@javax.annotation.Nonnull String country) {
        this.country = country;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        PersonAddress personAddress = (PersonAddress) o;
        return Objects.equals(this.street, personAddress.street)
                && Objects.equals(this.postalCode, personAddress.postalCode)
                && Objects.equals(this.region, personAddress.region)
                && Objects.equals(this.country, personAddress.country);
    }

    @Override
    public int hashCode() {
        return Objects.hash(street, postalCode, region, country);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class PersonAddress {\n");
        sb.append("    street: ").append(toIndentedString(street)).append("\n");
        sb.append("    postalCode: ").append(toIndentedString(postalCode)).append("\n");
        sb.append("    region: ").append(toIndentedString(region)).append("\n");
        sb.append("    country: ").append(toIndentedString(country)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces (except the first
     * line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    /**
     * Convert the instance into URL query string.
     *
     * @return URL query string
     */
    public String toUrlQueryString() {
        return toUrlQueryString(null);
    }

    /**
     * Convert the instance into URL query string.
     *
     * @param prefix prefix of the query string
     * @return URL query string
     */
    public String toUrlQueryString(String prefix) {
        String suffix = "";
        String containerSuffix = "";
        String containerPrefix = "";
        if (prefix == null) {
            // style=form, explode=true, e.g. /pet?name=cat&type=manx
            prefix = "";
        } else {
            // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
            prefix = prefix + "[";
            suffix = "]";
            containerSuffix = "]";
            containerPrefix = "[";
        }

        StringJoiner joiner = new StringJoiner("&");

        // add `street` to the URL query string
        if (getStreet() != null) {
            try {
                joiner.add(
                        String.format(
                                java.util.Locale.ROOT,
                                "%sstreet%s=%s",
                                prefix,
                                suffix,
                                URLEncoder.encode(String.valueOf(getStreet()), "UTF-8")
                                        .replaceAll("\\+", "%20")));
            } catch (UnsupportedEncodingException e) {
                // Should never happen, UTF-8 is always supported
                throw new RuntimeException(e);
            }
        }

        // add `postal-code` to the URL query string
        if (getPostalCode() != null) {
            try {
                joiner.add(
                        String.format(
                                java.util.Locale.ROOT,
                                "%spostal-code%s=%s",
                                prefix,
                                suffix,
                                URLEncoder.encode(String.valueOf(getPostalCode()), "UTF-8")
                                        .replaceAll("\\+", "%20")));
            } catch (UnsupportedEncodingException e) {
                // Should never happen, UTF-8 is always supported
                throw new RuntimeException(e);
            }
        }

        // add `region` to the URL query string
        if (getRegion() != null) {
            try {
                joiner.add(
                        String.format(
                                java.util.Locale.ROOT,
                                "%sregion%s=%s",
                                prefix,
                                suffix,
                                URLEncoder.encode(String.valueOf(getRegion()), "UTF-8")
                                        .replaceAll("\\+", "%20")));
            } catch (UnsupportedEncodingException e) {
                // Should never happen, UTF-8 is always supported
                throw new RuntimeException(e);
            }
        }

        // add `country` to the URL query string
        if (getCountry() != null) {
            try {
                joiner.add(
                        String.format(
                                java.util.Locale.ROOT,
                                "%scountry%s=%s",
                                prefix,
                                suffix,
                                URLEncoder.encode(String.valueOf(getCountry()), "UTF-8")
                                        .replaceAll("\\+", "%20")));
            } catch (UnsupportedEncodingException e) {
                // Should never happen, UTF-8 is always supported
                throw new RuntimeException(e);
            }
        }

        return joiner.toString();
    }

    public static class Builder {

        private PersonAddress instance;

        public Builder() {
            this(new PersonAddress());
        }

        protected Builder(PersonAddress instance) {
            this.instance = instance;
        }

        public PersonAddress.Builder street(String street) {
            this.instance.street = street;
            return this;
        }

        public PersonAddress.Builder postalCode(String postalCode) {
            this.instance.postalCode = postalCode;
            return this;
        }

        public PersonAddress.Builder region(String region) {
            this.instance.region = region;
            return this;
        }

        public PersonAddress.Builder country(String country) {
            this.instance.country = country;
            return this;
        }

        /**
         * returns a built PersonAddress instance.
         *
         * <p>The builder is not reusable.
         */
        public PersonAddress build() {
            try {
                return this.instance;
            } finally {
                // ensure that this.instance is not reused
                this.instance = null;
            }
        }

        @Override
        public String toString() {
            return getClass() + "=(" + instance + ")";
        }
    }

    /** Create a builder with no initialized field. */
    public static PersonAddress.Builder builder() {
        return new PersonAddress.Builder();
    }

    /** Create a builder with a shallow copy of this instance. */
    public PersonAddress.Builder toBuilder() {
        return new PersonAddress.Builder()
                .street(getStreet())
                .postalCode(getPostalCode())
                .region(getRegion())
                .country(getCountry());
    }
}
