/*
 * Definancy API
 * Specification version: 0.0.1.wip.20250925
 *
 * NOTE: This class is auto generated by our custom generator.
 * Do not edit the class manually.
 */


package com.definancy.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import java.util.Locale;
import com.definancy.model.PersonNaturalIdType;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.definancy.JSON;


/**
 * Government-issued identification document details for individual identity verification including document number, type, and issuing authority.
 */
@JsonPropertyOrder({
  PersonNaturalId.JSON_PROPERTY_NUMBER,
  PersonNaturalId.JSON_PROPERTY_TYPE,
  PersonNaturalId.JSON_PROPERTY_ISSUER
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.16.0-SNAPSHOT")
public class PersonNaturalId {
  public static final String JSON_PROPERTY_NUMBER = "number";
  @javax.annotation.Nonnull
  private String number;

  public static final String JSON_PROPERTY_TYPE = "type";
  @javax.annotation.Nonnull
  private PersonNaturalIdType type;

  public static final String JSON_PROPERTY_ISSUER = "issuer";
  @javax.annotation.Nonnull
  private String issuer;

  public PersonNaturalId() { 
  }

  public PersonNaturalId number(@javax.annotation.Nonnull String number) {
    this.number = number;
    return this;
  }

  /**
   * Identification document number.
   * @return number
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_NUMBER, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getNumber() {
    return number;
  }


  @JsonProperty(value = JSON_PROPERTY_NUMBER, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setNumber(@javax.annotation.Nonnull String number) {
    this.number = number;
  }


  public PersonNaturalId type(@javax.annotation.Nonnull PersonNaturalIdType type) {
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public PersonNaturalIdType getType() {
    return type;
  }


  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setType(@javax.annotation.Nonnull PersonNaturalIdType type) {
    this.type = type;
  }


  public PersonNaturalId issuer(@javax.annotation.Nonnull String issuer) {
    this.issuer = issuer;
    return this;
  }

  /**
   * Identification issuing authority.
   * @return issuer
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ISSUER, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getIssuer() {
    return issuer;
  }


  @JsonProperty(value = JSON_PROPERTY_ISSUER, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setIssuer(@javax.annotation.Nonnull String issuer) {
    this.issuer = issuer;
  }


  /**
   * Return true if this PersonNaturalId object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PersonNaturalId personNaturalId = (PersonNaturalId) o;
    return Objects.equals(this.number, personNaturalId.number) &&
        Objects.equals(this.type, personNaturalId.type) &&
        Objects.equals(this.issuer, personNaturalId.issuer);
  }

  @Override
  public int hashCode() {
    return Objects.hash(number, type, issuer);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PersonNaturalId {\n");
    sb.append("    number: ").append(toIndentedString(number)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    issuer: ").append(toIndentedString(issuer)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

