/*
 * Definancy API
 * REST API for managing asset, network and contract configurations, and vault-based financial operations. This API provides a comprehensive set of endpoints for health monitoring, network management, asset  configuration, contract management, vault lifecycle management, and QR-Code generation. It is designed to facilitate seamless integration with financial systems, ensuring secure and efficient payment  processing while maintaining strict compliance standards.
 *
 * The version of the OpenAPI document: 0.0.1.wip.20250925
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.definancy.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.util.Objects;
import java.util.StringJoiner;

/**
 * Business registration and identification information for legal entities. Contains official
 * registration details required for entity verification and compliance with business identification
 * regulations.
 */
@JsonPropertyOrder({
    PersonLegalId.JSON_PROPERTY_NUMBER,
    PersonLegalId.JSON_PROPERTY_TYPE,
    PersonLegalId.JSON_PROPERTY_ISSUER
})
@javax.annotation.Generated(
        value = "org.openapitools.codegen.languages.JavaClientCodegen",
        comments = "Generator version: 7.20.0")
public class PersonLegalId {
    public static final String JSON_PROPERTY_NUMBER = "number";
    @javax.annotation.Nonnull private String number;

    public static final String JSON_PROPERTY_TYPE = "type";
    @javax.annotation.Nonnull private PersonLegalIdType type;

    public static final String JSON_PROPERTY_ISSUER = "issuer";
    @javax.annotation.Nonnull private String issuer;

    public PersonLegalId() {}

    /** Constructor with all args parameters */
    public PersonLegalId(
            @JsonProperty(value = JSON_PROPERTY_NUMBER, required = true) String number,
            @JsonProperty(value = JSON_PROPERTY_TYPE, required = true) PersonLegalIdType type,
            @JsonProperty(value = JSON_PROPERTY_ISSUER, required = true) String issuer) {
        this.number = number;
        this.type = type;
        this.issuer = issuer;
    }

    public PersonLegalId number(@javax.annotation.Nonnull String number) {

        this.number = number;
        return this;
    }

    /**
     * Official business registration number, tax identification number, or other government-issued
     * entity identifier exactly as it appears on official documentation.
     *
     * @return number
     */
    @javax.annotation.Nonnull
    @JsonProperty(value = JSON_PROPERTY_NUMBER, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public String getNumber() {
        return number;
    }

    @JsonProperty(value = JSON_PROPERTY_NUMBER, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setNumber(@javax.annotation.Nonnull String number) {
        this.number = number;
    }

    public PersonLegalId type(@javax.annotation.Nonnull PersonLegalIdType type) {

        this.type = type;
        return this;
    }

    /**
     * Get type
     *
     * @return type
     */
    @javax.annotation.Nonnull
    @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public PersonLegalIdType getType() {
        return type;
    }

    @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setType(@javax.annotation.Nonnull PersonLegalIdType type) {
        this.type = type;
    }

    public PersonLegalId issuer(@javax.annotation.Nonnull String issuer) {

        this.issuer = issuer;
        return this;
    }

    /**
     * Government authority, tax agency, or business registration office that issued the legal
     * entity identification. Used for verification and authenticity validation purposes.
     *
     * @return issuer
     */
    @javax.annotation.Nonnull
    @JsonProperty(value = JSON_PROPERTY_ISSUER, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public String getIssuer() {
        return issuer;
    }

    @JsonProperty(value = JSON_PROPERTY_ISSUER, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setIssuer(@javax.annotation.Nonnull String issuer) {
        this.issuer = issuer;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        PersonLegalId personLegalId = (PersonLegalId) o;
        return Objects.equals(this.number, personLegalId.number)
                && Objects.equals(this.type, personLegalId.type)
                && Objects.equals(this.issuer, personLegalId.issuer);
    }

    @Override
    public int hashCode() {
        return Objects.hash(number, type, issuer);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class PersonLegalId {\n");
        sb.append("    number: ").append(toIndentedString(number)).append("\n");
        sb.append("    type: ").append(toIndentedString(type)).append("\n");
        sb.append("    issuer: ").append(toIndentedString(issuer)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces (except the first
     * line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    /**
     * Convert the instance into URL query string.
     *
     * @return URL query string
     */
    public String toUrlQueryString() {
        return toUrlQueryString(null);
    }

    /**
     * Convert the instance into URL query string.
     *
     * @param prefix prefix of the query string
     * @return URL query string
     */
    public String toUrlQueryString(String prefix) {
        String suffix = "";
        String containerSuffix = "";
        String containerPrefix = "";
        if (prefix == null) {
            // style=form, explode=true, e.g. /pet?name=cat&type=manx
            prefix = "";
        } else {
            // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
            prefix = prefix + "[";
            suffix = "]";
            containerSuffix = "]";
            containerPrefix = "[";
        }

        StringJoiner joiner = new StringJoiner("&");

        // add `number` to the URL query string
        if (getNumber() != null) {
            try {
                joiner.add(
                        String.format(
                                java.util.Locale.ROOT,
                                "%snumber%s=%s",
                                prefix,
                                suffix,
                                URLEncoder.encode(String.valueOf(getNumber()), "UTF-8")
                                        .replaceAll("\\+", "%20")));
            } catch (UnsupportedEncodingException e) {
                // Should never happen, UTF-8 is always supported
                throw new RuntimeException(e);
            }
        }

        // add `type` to the URL query string
        if (getType() != null) {
            try {
                joiner.add(
                        String.format(
                                java.util.Locale.ROOT,
                                "%stype%s=%s",
                                prefix,
                                suffix,
                                URLEncoder.encode(String.valueOf(getType()), "UTF-8")
                                        .replaceAll("\\+", "%20")));
            } catch (UnsupportedEncodingException e) {
                // Should never happen, UTF-8 is always supported
                throw new RuntimeException(e);
            }
        }

        // add `issuer` to the URL query string
        if (getIssuer() != null) {
            try {
                joiner.add(
                        String.format(
                                java.util.Locale.ROOT,
                                "%sissuer%s=%s",
                                prefix,
                                suffix,
                                URLEncoder.encode(String.valueOf(getIssuer()), "UTF-8")
                                        .replaceAll("\\+", "%20")));
            } catch (UnsupportedEncodingException e) {
                // Should never happen, UTF-8 is always supported
                throw new RuntimeException(e);
            }
        }

        return joiner.toString();
    }

    public static class Builder {

        private PersonLegalId instance;

        public Builder() {
            this(new PersonLegalId());
        }

        protected Builder(PersonLegalId instance) {
            this.instance = instance;
        }

        public PersonLegalId.Builder number(String number) {
            this.instance.number = number;
            return this;
        }

        public PersonLegalId.Builder type(PersonLegalIdType type) {
            this.instance.type = type;
            return this;
        }

        public PersonLegalId.Builder issuer(String issuer) {
            this.instance.issuer = issuer;
            return this;
        }

        /**
         * returns a built PersonLegalId instance.
         *
         * <p>The builder is not reusable.
         */
        public PersonLegalId build() {
            try {
                return this.instance;
            } finally {
                // ensure that this.instance is not reused
                this.instance = null;
            }
        }

        @Override
        public String toString() {
            return getClass() + "=(" + instance + ")";
        }
    }

    /** Create a builder with no initialized field. */
    public static PersonLegalId.Builder builder() {
        return new PersonLegalId.Builder();
    }

    /** Create a builder with a shallow copy of this instance. */
    public PersonLegalId.Builder toBuilder() {
        return new PersonLegalId.Builder().number(getNumber()).type(getType()).issuer(getIssuer());
    }
}
