/*
 * Definancy Node API
 * Specification version: 0.0.1.wip.20250826
 *
 * NOTE: This class is auto generated by our custom generator.
 * Do not edit the class manually.
 */


package com.definancy.model;

import java.util.Objects;
import java.util.Locale;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import java.util.Locale;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Data encoding format used in the QR code content.  Currently supports raw byte encoding for maximum compatibility  with cryptocurrency wallets.
 */
@JsonAdapter(QrCodeEncoding.Adapter.class)
public enum QrCodeEncoding {
  
  BYTE("byte");

  private String value;

  QrCodeEncoding(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static QrCodeEncoding fromValue(String value) {
    for (QrCodeEncoding b : QrCodeEncoding.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<QrCodeEncoding> {
    @Override
    public void write(final JsonWriter jsonWriter, final QrCodeEncoding enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public QrCodeEncoding read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return QrCodeEncoding.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    QrCodeEncoding.fromValue(value);
  }
}

